package com.cursojava.proyecto.utils.herencia;

public class Normal extends Movimiento {

    public Normal(){
        super();
        movimientos.add("Acupresión");
        movimientos.add("Adaptación");
        movimientos.add("Afilar");
        movimientos.add("Agarre");
        movimientos.add("Agarrón");
        movimientos.add("Aguante");
        movimientos.add("Aguzar");
        movimientos.add("Alboroto");
        movimientos.add("Alivio");
        movimientos.add("Amago");
        movimientos.add("Amortiguador");
        movimientos.add("Antojo");
        movimientos.add("Anulación");
        movimientos.add("Arañazo");
        movimientos.add("Ariete");
        movimientos.add("Arrojo intempestivo");
        movimientos.add("As oculto");
        movimientos.add("Atadura");
        movimientos.add("Ataque furia");
        movimientos.add("Ataque rápido");
        movimientos.add("Atiborramiento");
        movimientos.add("Atizar");
        movimientos.add("Atracción");
        movimientos.add("Aullido");
        movimientos.add("Autodestrucción");
        movimientos.add("Avivar");
        movimientos.add("Ayuda");
        movimientos.add("Azote");
        movimientos.add("Batido");
        movimientos.add("Beso amoroso");
        movimientos.add("Bloqueo");
        movimientos.add("Bomba huevo");
        movimientos.add("Bomba sónica");
        movimientos.add("Bostezo");
        movimientos.add("Cabezazo");
        movimientos.add("Cambio de cancha");
        movimientos.add("Camaradería");
        movimientos.add("Campana cura");
        movimientos.add("Camuflaje");
        movimientos.add("Canon");
        movimientos.add("Canto");
        movimientos.add("Canto arcaico");
        movimientos.add("Canto mortal");
        movimientos.add("Cara susto");
        movimientos.add("Carrera arrolladora");
        movimientos.add("Cede paso");
        movimientos.add("Celebración");
        movimientos.add("Chirrido");
        movimientos.add("Clavo cañón");
        movimientos.add("Clemencia");
        movimientos.add("Clonatipo");
        movimientos.add("Confidencia");
        movimientos.add("Conjuro");
        movimientos.add("Contoneo");
        movimientos.add("Conversión");
        movimientos.add("Conversión2");
        movimientos.add("Copión");
        movimientos.add("Cornada");
        movimientos.add("Corte");
        movimientos.add("Cosquillas");
        movimientos.add("Cuchillada");
        movimientos.add("Danza amiga");
        movimientos.add("Danza caos");
        movimientos.add("Danza despertar");
        movimientos.add("Danza espada");
        movimientos.add("Daño secreto");
        movimientos.add("Derribo");
        movimientos.add("Desarrollo");
        movimientos.add("Deseo");
        movimientos.add("Deslumbrar");
        movimientos.add("Destello");
        movimientos.add("Destructor");
        movimientos.add("Día de pago");
        movimientos.add("Divide dolor");
        movimientos.add("Doble equipo");
        movimientos.add("Doble filo");
        movimientos.add("Doble golpe");
        movimientos.add("Doble bofetón");
        movimientos.add("Don natural");
        movimientos.add("Dulce aroma");
        movimientos.add("Eco voz");
        movimientos.add("Escupir");
        movimientos.add("Esfuerzo");
        movimientos.add("Esquema");
        movimientos.add("Estímulo");
        movimientos.add("Estruendo");
        movimientos.add("Estrujón");
        movimientos.add("Explosión");
        movimientos.add("Falsotortazo");
        movimientos.add("Fijar blanco");
        movimientos.add("Foco");
        movimientos.add("Foco energía");
        movimientos.add("Fortaleza");
        movimientos.add("Frustración");
        movimientos.add("Fuerza");
        movimientos.add("Furia");
        movimientos.add("Garra brutal");
        movimientos.add("Giga impacto");
        movimientos.add("Giro rápido");
        movimientos.add("Golpe");
        movimientos.add("Golpe cabeza");
        movimientos.add("Golpe cuerpo");
        movimientos.add("Golpes furia");
        movimientos.add("Gruñido");
        movimientos.add("Guardia baja");
        movimientos.add("Guillotina");
        movimientos.add("Hiper colmillo");
        movimientos.add("Hiperrayo");
        movimientos.add("Hora del té");
        movimientos.add("Imagen");
        movimientos.add("Látigo");
        movimientos.add("Mal de ojo");
        movimientos.add("Malicioso");
        movimientos.add("Manos juntas");
        movimientos.add("Más psique");
        movimientos.add("Megapatada");
        movimientos.add("Megapuño");
        movimientos.add("Meteorobola");
        movimientos.add("Metrónomo");
        movimientos.add("Mimético");
        movimientos.add("Multiataque");
        movimientos.add("Novena potencia");
        movimientos.add("Ofrenda");
        movimientos.add("Ojos llorosos");
        movimientos.add("Onda simple");
        movimientos.add("Otra vez");
        movimientos.add("Paga extra");
        movimientos.add("Pantalla de humo");
        movimientos.add("Perforador");
        movimientos.add("Pisotón");
        movimientos.add("Placaje");
        movimientos.add("Plumerazo");
        movimientos.add("Poder oculto");
        movimientos.add("Presa");
        movimientos.add("Presente");
        movimientos.add("Profecía");
        movimientos.add("Protección");
        movimientos.add("Puño cometa");
        movimientos.add("Puño mareo");
        movimientos.add("Rapidez");
        movimientos.add("Rastreo");
        movimientos.add("Reciclaje");
        movimientos.add("Recuperación");
        movimientos.add("Reducción");
        movimientos.add("Refuerzo");
        movimientos.add("Relajo");
        movimientos.add("Relevo");
        movimientos.add("Remolino");
        movimientos.add("Constricción");
        movimientos.add("Represalia");
        movimientos.add("Reserva");
        movimientos.add("Restricción");
        movimientos.add("Retribución");
        movimientos.add("Rizo defensa");
        movimientos.add("Rompecoraza");
        movimientos.add("Ronquido");
        movimientos.add("Rugido");
        movimientos.add("Rugido de guerra");
        movimientos.add("Salpicadura");
        movimientos.add("Seducción");
        movimientos.add("Sentencia");
        movimientos.add("Señuelo");
        movimientos.add("Sol matinal");
        movimientos.add("Sonámbulo");
        movimientos.add("Sorpresa");
        movimientos.add("Superdiente");
        movimientos.add("Supersónico");
        movimientos.add("Sustituto");
        movimientos.add("Tambor");
        movimientos.add("Tecno shock");
        movimientos.add("Telépata");
        movimientos.add("Tragar");
        movimientos.add("Transformación");
        movimientos.add("Treparrocas");
        movimientos.add("Triataque");
        movimientos.add("Última baza");
        movimientos.add("Velo sagrado");
        movimientos.add("Velocidad extrema");
        movimientos.add("Venganza");
        movimientos.add("Viento cortante");
        movimientos.add("Vozarrón");
        movimientos.add("Yo primero");
    }
}
