#actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,loggers,metrics,mappings #loggers, metrics y mappings agregados al actuator
  info:
    env:
      enabled: true
#Informacion del proyecto
info:
  app:
    name: LeaningJava API
  java:
    version: 1.0
  type: Spring Boot

consumers:
  login: '/api/login'
  createUser: '/api/createUser'
  createUsers: '/api/createUsers'
  userAccount: '/api/getUserAccount'
  accounts: '/api/getAccounts'
  accountsGroupByType: '/api/getAccountsGroupByType'

spring:
  h2:
    console: 
      enabled:
        true
  datasource:
    url:
    jdbc:
      h2:
        mem:
          testdb
  data:
    mongodb:
      #host: host.docker.internal
      port: 27017
  batch:
    job:
      enabled: false 
        
server:
  port: 8080
