# Configuration data loaded from a Config-server
spring:
  application:
    name: LearningJava
  profiles:
    include: dev
  security:
    white-list:
      url: /authenticate, /swagger-ui/**, /v3/api-docs/**, /api/getAccounts, /actuator/**, /api/getEncryptedAccounts, /api/getAccountsByUser, /api/createAccount, /api/createUser, /api/login, /api/getUserAccount, /dising_patterns/api/prototype, /dising_patterns/api/singleton, /api/users
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    mongodb:
      database: baz-bootcamp
      port: 27017

server:
  port: 8080

jwt:
  secret: java-baz

# Revisión: Exponer tres endpoints de Actuator (e.g. metrics, mappings, loggers)
#Se habilitan los endpoints a exponer en actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env,metrics,mappings,loggers
  info:
    env:
      enabled: true

# Revisión: Exponer la información del proyecto mediante el endpoint Info de Actuator
#Informacion del proyeecto
info:
  app:
    name: LearningJavaMaven API
    java:
      version: 1.0
    type: Spring Boot
