
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
  data:
    mongodb:
      port: 27017
      database: baz-wizeline
  security:
    white-list:
      url: "/authenticate, /swagger-ui/**, /v3/api-docs/**, /api/getAccounts, /actuator/**"
  
# Información del proyecto
info:
  app:
    name: LearningSpring API
    java: version=1.0
    type: Spring Boot

server:
  port: 8080

jwt:
  secret: java-baz

# Se habilitan endpoints a exponer en actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,beans,env
  info:
    env:
      enabled: true